package org.omg.IOP;


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u45/3457/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, April 10, 2015 10:49:22 AM PDT
*/

public interface RMICustomMaxStreamFormat
{

  /**
       * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
       * service context which contains a single byte specifying
       * the client's maximum RMI-IIOP stream format version.
       *
       * See Java to IDL ptc/02-01-12 1.4.12.
       */
  public static final int value = (int)(17L);
}
