package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/InitialNameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u45/3457/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Friday, April 10, 2015 10:49:20 AM PDT
*/

public interface InitialNameService extends InitialNameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InitialNameService
